# Suggested by https://scikit-hep.org/developer/gha_wheels
[tool.cibuildwheel]
# Disable building PyPy wheels on all platforms
skip = "pp*"
test-requires = "pytest"
test-command = "pytest {package}/test.py"
build-verbosity = 1

[tool.cibuildwheel.linux]
before-build = [
    "yum install -y ncurses-devel",
    "make clean",
]

[tool.cibuildwheel.macos]
before-build = [
    "brew install ncurses",
    "make clean",
]
# Support Universal2 = Intel + ARM for Apple Silicon (but don't test it yet)
archs = ["auto", "universal2"]
test-skip = ["*universal2:arm64"]
